"""Pagrindiniai žodynai, naudojami programoje dirbant su yfinance.

Visi kodai (pvz. PRICE, REVENUE) yra susieti su konkrečiais duomenų
šaltiniais. Tai leidžia programai generiškai gauti reikšmes bei jas
formatuoti arba naudoti grafikuose.
"""

YFINANCE_SERIJOS = {
    "PRICE": {
        "label": "Dabartinė kaina ($)",
        "category": "Kaina ir rinka",
        "source": "fast_info",
        "field": "lastPrice",
        "format": "usd",
        "precision": 2,
        "plot": False,
    },
    "MARKET_CAP": {
        "label": "Kapitalizacija ($)",
        "category": "Kaina ir rinka",
        "source": "fast_info",
        "field": "marketCap",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "SHARES_OUTSTANDING": {
        "label": "Akcijų skaičius",
        "category": "Kaina ir rinka",
        "source": "fast_info",
        "field": "sharesOutstanding",
        "format": "number",
        "precision": 0,
        "plot": False,
    },
    "EPS": {
        "label": "EPS",
        "category": "Pelningumas",
        "source": "info",
        "field": "trailingEps",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "REVENUE": {
        "label": "Pajamos ($)",
        "category": "Augimas",
        "source": "income_stmt",
        "field": "Total Revenue",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "NET_INCOME": {
        "label": "Grynasis pelnas ($)",
        "category": "Augimas",
        "source": "income_stmt",
        "field": "Net Income",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "EBITDA": {
        "label": "EBITDA ($)",
        "category": "Pelningumas",
        "source": "income_stmt",
        "field": "Ebitda",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "GROSS_PROFIT": {
        "label": "Bendrasis pelnas ($)",
        "category": "Pelningumas",
        "source": "income_stmt",
        "field": "Gross Profit",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "OPERATING_INCOME": {
        "label": "Operacinis pelnas ($)",
        "category": "Pelningumas",
        "source": "income_stmt",
        "field": "Operating Income",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "OPERATING_CASH_FLOW": {
        "label": "Operacinis pinigų srautas ($)",
        "category": "Pinigų srautai",
        "source": "cash_flow",
        "field": "Total Cash From Operating Activities",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "CAPEX": {
        "label": "Kapitalo išlaidos ($)",
        "category": "Pinigų srautai",
        "source": "cash_flow",
        "field": "Capital Expenditures",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "FREE_CASH_FLOW": {
        "label": "Laisvas pinigų srautas ($)",
        "category": "Pinigų srautai",
        "source": "derived",
        "formula": "add",
        "operands": ["OPERATING_CASH_FLOW", "CAPEX"],
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "TOTAL_ASSETS": {
        "label": "Turtas ($)",
        "category": "Balansas",
        "source": "balance_sheet",
        "field": "Total Assets",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "TOTAL_LIABILITIES": {
        "label": "Visos skolos ($)",
        "category": "Balansas",
        "source": "balance_sheet",
        "field": "Total Liab",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "TOTAL_EQUITY": {
        "label": "Nuosavas kapitalas ($)",
        "category": "Balansas",
        "source": "balance_sheet",
        "field": "Total Stockholder Equity",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "TOTAL_DEBT": {
        "label": "Bendros skolos ($)",
        "category": "Balansas",
        "source": "balance_sheet",
        "field": "Total Debt",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "CURRENT_ASSETS": {
        "label": "Trumpalaikis turtas ($)",
        "category": "Likvidumas",
        "source": "balance_sheet",
        "field": "Total Current Assets",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "CURRENT_LIABILITIES": {
        "label": "Trumpalaikiai įsipareigojimai ($)",
        "category": "Likvidumas",
        "source": "balance_sheet",
        "field": "Total Current Liabilities",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "CASH_EQUIVALENTS": {
        "label": "Grynieji ir ekvivalentai ($)",
        "category": "Likvidumas",
        "source": "balance_sheet",
        "field": "Cash And Cash Equivalents",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "PE_RATIO": {
        "label": "P/E",
        "category": "Vertinimas",
        "source": "derived",
        "formula": "divide",
        "numerator": "PRICE",
        "denominator": "EPS",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "ROE": {
        "label": "ROE (%)",
        "category": "Pelningumas",
        "source": "derived",
        "formula": "divide",
        "numerator": "NET_INCOME",
        "denominator": "TOTAL_EQUITY",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
    "ROA": {
        "label": "ROA (%)",
        "category": "Pelningumas",
        "source": "derived",
        "formula": "divide",
        "numerator": "NET_INCOME",
        "denominator": "TOTAL_ASSETS",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
    "NET_MARGIN": {
        "label": "Grynojo pelno marža (%)",
        "category": "Pelningumas",
        "source": "derived",
        "formula": "divide",
        "numerator": "NET_INCOME",
        "denominator": "REVENUE",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
    "CURRENT_RATIO": {
        "label": "Current Ratio",
        "category": "Likvidumas",
        "source": "derived",
        "formula": "divide",
        "numerator": "CURRENT_ASSETS",
        "denominator": "CURRENT_LIABILITIES",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "DEBT_TO_EQUITY": {
        "label": "Debt/Equity",
        "category": "Skolos",
        "source": "derived",
        "formula": "divide",
        "numerator": "TOTAL_DEBT",
        "denominator": "TOTAL_EQUITY",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "DEBT_TO_EBITDA": {
        "label": "Debt/EBITDA",
        "category": "Skolos",
        "source": "derived",
        "formula": "divide",
        "numerator": "TOTAL_DEBT",
        "denominator": "EBITDA",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "FREE_CASH_FLOW_MARGIN": {
        "label": "FCF marža (%)",
        "category": "Pinigų srautai",
        "source": "derived",
        "formula": "divide",
        "numerator": "FREE_CASH_FLOW",
        "denominator": "REVENUE",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
}
