"""Paprastas žodynas su visais palaikomais rodikliais.

Kiekvienas įrašas dirba su viena yfinance duomenų dalimi. Pagrindiniai
raktai:
- label: kaip rodiklis bus rodomas ekrane ar Excel'e.
- group: santraukos lentelėje naudojama skiltis.
- type: "raw" (tiesiog paimama reikšmė) arba "formula" (skaičiuojama).
- source / field: kur ieškoti reikšmės (fast_info, info, income_stmt ir t. t.).
- format: kaip spausdinti (usd, percent, number).
- plot: ar galima naudoti grafikams.
"""

YFINANCE_SERIJOS = {
    "PRICE": {
        "label": "Dabartinė kaina ($)",
        "group": "Kaina ir rinka",
        "type": "raw",
        "source": "fast_info",
        "field": "lastPrice",
        "format": "usd",
        "precision": 2,
        "plot": False,
    },
    "MARKET_CAP": {
        "label": "Kapitalizacija ($)",
        "group": "Kaina ir rinka",
        "type": "raw",
        "source": "fast_info",
        "field": "marketCap",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "SHARES_OUTSTANDING": {
        "label": "Akcijų skaičius",
        "group": "Kaina ir rinka",
        "type": "raw",
        "source": "fast_info",
        "field": "sharesOutstanding",
        "format": "number",
        "precision": 0,
        "plot": False,
    },
    "EPS": {
        "label": "EPS",
        "group": "Pelningumas",
        "type": "raw",
        "source": "info",
        "field": "trailingEps",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "REVENUE": {
        "label": "Pajamos ($)",
        "group": "Augimas",
        "type": "raw",
        "source": "income_stmt",
        "field": "Total Revenue",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "NET_INCOME": {
        "label": "Grynasis pelnas ($)",
        "group": "Augimas",
        "type": "raw",
        "source": "income_stmt",
        "field": "Net Income",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "GROSS_PROFIT": {
        "label": "Bendrasis pelnas ($)",
        "group": "Pelningumas",
        "type": "raw",
        "source": "income_stmt",
        "field": "Gross Profit",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "EBITDA": {
        "label": "EBITDA ($)",
        "group": "Pelningumas",
        "type": "raw",
        "source": "income_stmt",
        "field": "Ebitda",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "OPERATING_INCOME": {
        "label": "Operacinis pelnas ($)",
        "group": "Pelningumas",
        "type": "raw",
        "source": "income_stmt",
        "field": "Operating Income",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "OPERATING_CASH_FLOW": {
        "label": "Operacinis pinigų srautas ($)",
        "group": "Pinigų srautai",
        "type": "raw",
        "source": "cash_flow",
        "field": "Total Cash From Operating Activities",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "CAPEX": {
        "label": "Kapitalo išlaidos ($)",
        "group": "Pinigų srautai",
        "type": "raw",
        "source": "cash_flow",
        "field": "Capital Expenditures",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "FREE_CASH_FLOW": {
        "label": "Laisvas pinigų srautas ($)",
        "group": "Pinigų srautai",
        "type": "formula",
        "method": "sum",
        "operands": ["OPERATING_CASH_FLOW", "CAPEX"],
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "TOTAL_ASSETS": {
        "label": "Turtas ($)",
        "group": "Balansas",
        "type": "raw",
        "source": "balance_sheet",
        "field": "Total Assets",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "TOTAL_LIABILITIES": {
        "label": "Visos skolos ($)",
        "group": "Balansas",
        "type": "raw",
        "source": "balance_sheet",
        "field": "Total Liab",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "TOTAL_EQUITY": {
        "label": "Nuosavas kapitalas ($)",
        "group": "Balansas",
        "type": "raw",
        "source": "balance_sheet",
        "field": "Total Stockholder Equity",
        "format": "usd",
        "precision": 0,
        "plot": True,
    },
    "TOTAL_DEBT": {
        "label": "Bendros skolos ($)",
        "group": "Skolos",
        "type": "raw",
        "source": "balance_sheet",
        "field": "Total Debt",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "CURRENT_ASSETS": {
        "label": "Trumpalaikis turtas ($)",
        "group": "Likvidumas",
        "type": "raw",
        "source": "balance_sheet",
        "field": "Total Current Assets",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "CURRENT_LIABILITIES": {
        "label": "Trumpalaikiai įsipareigojimai ($)",
        "group": "Likvidumas",
        "type": "raw",
        "source": "balance_sheet",
        "field": "Total Current Liabilities",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "CASH_EQUIVALENTS": {
        "label": "Grynieji ir ekvivalentai ($)",
        "group": "Likvidumas",
        "type": "raw",
        "source": "balance_sheet",
        "field": "Cash And Cash Equivalents",
        "format": "usd",
        "precision": 0,
        "plot": False,
    },
    "PE_RATIO": {
        "label": "P/E",
        "group": "Vertinimas",
        "type": "formula",
        "method": "divide",
        "numerator": "PRICE",
        "denominator": "EPS",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "ROE": {
        "label": "ROE (%)",
        "group": "Pelningumas",
        "type": "formula",
        "method": "divide",
        "numerator": "NET_INCOME",
        "denominator": "TOTAL_EQUITY",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
    "ROA": {
        "label": "ROA (%)",
        "group": "Pelningumas",
        "type": "formula",
        "method": "divide",
        "numerator": "NET_INCOME",
        "denominator": "TOTAL_ASSETS",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
    "NET_MARGIN": {
        "label": "Grynojo pelno marža (%)",
        "group": "Pelningumas",
        "type": "formula",
        "method": "divide",
        "numerator": "NET_INCOME",
        "denominator": "REVENUE",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
    "CURRENT_RATIO": {
        "label": "Current Ratio",
        "group": "Likvidumas",
        "type": "formula",
        "method": "divide",
        "numerator": "CURRENT_ASSETS",
        "denominator": "CURRENT_LIABILITIES",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "DEBT_TO_EQUITY": {
        "label": "Debt/Equity",
        "group": "Skolos",
        "type": "formula",
        "method": "divide",
        "numerator": "TOTAL_DEBT",
        "denominator": "TOTAL_EQUITY",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "DEBT_TO_EBITDA": {
        "label": "Debt/EBITDA",
        "group": "Skolos",
        "type": "formula",
        "method": "divide",
        "numerator": "TOTAL_DEBT",
        "denominator": "EBITDA",
        "format": "number",
        "precision": 2,
        "plot": False,
    },
    "FREE_CASH_FLOW_MARGIN": {
        "label": "FCF marža (%)",
        "group": "Pinigų srautai",
        "type": "formula",
        "method": "divide",
        "numerator": "FREE_CASH_FLOW",
        "denominator": "REVENUE",
        "multiplier": 100,
        "format": "percent",
        "precision": 2,
        "plot": False,
    },
}
